# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

  upload-logs-to-elastic:
    runs-on: ubuntu-latest
    needs: build-java
    if: always()
    steps:
    - name: Upload GitHub Action workflows logs to elastic
      uses: ameerdev21/upload-github-workflow-logs-to-elastic@1.0.13
      with:
        github_token: "${{ secrets.GITHUB }}"
        github_org: "ameerdev21"
        github_repository: "my-project"
        github_run_id: "${{ github.run_id }}"
        elastic_host: "${{ secrets.ELASTIC_HOST }}"
        elastic_api_key_id: "${{ secrets.ELASTIC_KEY_ID }}"
        elastic_api_key: "${{ secrets.ELASTIC_API_KEY }}"
        elastic_index: "ci-cd"
         
